# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_foottypes_mainshow_mustbuy_nav_shop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foottypes',
            table='axfFoottypes',
        ),
    ]
