# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20171218_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foottypes',
            table='axfFootypes',
        ),
    ]
