# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20171218_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foottypes',
            new_name='Foodtypes',
        ),
        migrations.AlterModelTable(
            name='foodtypes',
            table='axfFoodtypes',
        ),
    ]
