# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_goods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='axf-goods',
        ),
    ]
